[versions]
mod-version = "0.1.0"

# Fabric (Minecraft 1.21.1)
jdk = "21"
minecraft = "1.21.1"
fabric-loader = "0.16.0"

# Loom
loom = "1.7-SNAPSHOT"

# Meteor Client
meteor = "0.5.8"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version = "1.21.1+build.1:v2" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

meteor-client = { group = "meteordevelopment", name = "meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
